### ISSUE TITLE
[Linux] undefined macro: AC_LIBTOOL_WIN32_DLL

### ISSUE THREAD

**Issue by moldcraft** [paulej/AESCrypt#10]
```
.../AESCrypt/Linux$ autoreconf -ivf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:80: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:81: error: possibly undefined macro: AC_LIBTOOL_RC
configure.ac:82: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

----

```
$ uname -a
Linux h 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by moldcraft** [comment]
https://www.aescrypt.com/download/

[AES Crypt source code (Linux)](https://www.aescrypt.com/download/v3/linux/aescrypt-3.10.tgz) Works

**Comment by moldcraft** [comment]
Another issue I have with Ubuntu 16.04 is that the `.aes` files created before, can't be decrypted with Linux installer GUI version. The compiled version works fine.

**Comment by paulej** [comment]
If there are spaces in the pathname, that would be the reason. There is a Perl script in the GitHub source repo that addresses that, but it hasn't been added to the binary build. It's also not in the source code downloadable from aescrypt.com, but maintained in my private repo that will get published to aescrypt.com.

The GitHub source has deviated from my official source.

**Comment by pigsflew** [comment]
Hi @moldcraft To build this you'll need autoconf, automake, and libtool (Gnu's Autotools chain). Those 3 macros are provided by libtool.

**Comment by paulej** [comment]
I've been wondering for a while if we should move the bits that require those tools into a sub-directory and leaving only "configure" in the root directory to build things.  Most people (including me before the autotools stuff was introduced) do not have those tools installed.
