### ISSUE TITLE
Crashes on Mac

### ISSUE THREAD

**Issue by radiogorillaz** [paulej/AESCrypt#13]
Downloaded: "AES Crypt - GUI (Mac x86) (This is the version most newer Mac users want.)"
...and it crashes after install. I right-click then select "Open" talks about unknown dev hit "open/run" and can't get past that.

OS info:
Mac OSX 10.11.6
3.06 GHz Intel Core 2 Duo

Let me know if anyone needs more info.

**Comment by paulej** [comment]
Not sure what you mean by right-clicking and selecting open.  Did you put the lock icon on the dock?  To encrypt and decrypt on the Mac, one drags and drops files on the lock icon on the dock.  For more detailed instructions, see these instructions: https://www.aescrypt.com/documentation/AES%20Crypt%20User%20Guide.pdf.

I'm going to close this issue.  If you still need help, send email to support at packetizer.com.

**Comment by radiogorillaz** [comment]
Did not see this User Guide. So sorry for taking up your time!
