### ISSUE TITLE
Linux x64 ELF Installation Issues with Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by mmangione** [paulej/AESCrypt#17]
I can successfully execute the file AESCrypt-GUI-3.11-Linux-x86_64-Install. After prompting for my password, it exits silently with status 0 (from strace). Afterwards, no context entry is available when I right-click, and AESCrypt does not show up in my installed programs. Neither "aescrypt" nor "aescrypt-gui" are recognized commands.

I would debug this operation, but I'm not even sure where to begin. Why exit with status 0?

**Comment by mmangione** [comment]
Update: As I was closing all of my windows, I found that 6 installation dialog boxes had popped up behind my terminal window. This installation dialog did not insert an icon in my toolbar, nor was it accessible through ALT+TAB. This is a graphical window that is not noticeable by any means of normal inspection.

**Comment by paulej** [comment]
Yeah, I've seen that and don't know why it happens.  Sounds like it didn't install.  But, step through that dialog and it will

**Comment by mark-vypyrailo** [comment]
I have the same issue. When the installation dialog popped up my PC rebooted. Then I tried to install it again with no success. After some attempts I finally installed it. But what was that?

**Comment by paulej** [comment]
The installer used is an old open source package that's no longer maintained. I suspect some things broke over time. I need to find a new installer tool or just write a script to do it.

That installer does have the ability to install via the command line without using the GUI. That works, so it's just some compatibility issue with the installer's GUI code.
