### ISSUE TITLE
Publish signatures for all pre-compiled packages.

### ISSUE THREAD

**Issue by mmangione** [paulej/AESCrypt#19]
Please publish the signatures with all pre-compiled packages. We're relying on AESCrypt to protect secrets, so there should be a verifiable chain of trust for these packages.

**Comment by paulej** [comment]
The download page on aesceypt.com has a link to an off-site page that lists all file hashes and is signed by me using GPG.

**Comment by ghostArch** [comment]
>  using GPG

nice. that should solve the chain of trust issue, if it was considered while generating signature.

---

> a link to an off-site page

now, is there a bot that could help me find that link? till then I'll download and verify https://cryptomator.org/ as the hashes are easily found. the signatures are also easily found.

<details>
<summary>CLICK ME</summary>
<p>

#### yes, good website design is important unless you want to hide the hashes

this doesn't work on https://www.aescrypt.com/download/ as its too damn good at hiding the hashes.
and if not for https://github.com/paulej/AESCrypt/issues/19#issuecomment-388303329 I would never know that a link is present somewhere on the site.


```
site="https://www.aescrypt.com"
site.find_hashes()
```

now, a bot to look for the signatures and the public key.



</p>
</details>

**Comment by paulej** [comment]
The link is at the bottom of the download page on aescrypt.com.
