### ISSUE TITLE
Please clearly indicate license terms

### ISSUE THREAD

**Issue by IvanPizhenko** [paulej/AESCrypt#30]
Hi, I'd like to reuse parts of your code to create simular open source utility that just employs different encryption algorithm. However, I can't find any reference to exact license terms that this code is covered by. Can you please follow standard practice and add file called LICENSE in the root of your repo with exact license terms.

**Comment by paulej** [comment]
The aes.h/c and sha256.h/c files are GNU-licensed code that I incorporated.  The rest of the code is code I personally authored (along with folks who collaborated on it, some of whose names are listed in source files).  You're welcome to use that code as you wish, even for commercial use.

I cannot meet the license file request, simply because there are effectively two licenses here and I cannot extend freedoms beyond the GNU code to code I did not write.  I really hate the GNU license, as it's so restrictive.

**Comment by IvanPizhenko** [comment]
Thank you for that information. Because this is not declared, people like me have to ask such questions. 
Another thing is that generally, content of LICENSE file is not restricted in any way, so it just might state exactly what you've written above - that certain files are GPL licensed, and the rest are "public domain" or whatever. I'd also include standard disclaimer of liability. Btw, putting all this togeter, you would really fit into sort of BSD license (there are 2 popular variants:  2-clause and 3-clause) for all files except those which are GPL licensed ones.

**Comment by IvanPizhenko** [comment]
However, if you have incorporated that GPL stuff, it may turn that the whole work now **must** be licensed under GPL - this is according to GPL terms, otherwise you may be violating GPL. But you are free to put dual-licensing (GPL+BSD, GPL+public domain) on the rest of source code.

**Comment by IvanPizhenko** [comment]
I personally also interested in the code that is not GPL'ed, BSD or Apache or MIT license would be ideal fit.

**Comment by paulej** [comment]
Yeah, the issue really is the GNU license.  It forces a requirement that anything compiled against it is also GPL.  It's a nasty license and I intend to get rid of it once day.  I have that and a number of other things on my to-do list.

**Comment by IvanPizhenko** [comment]
What I am trying to say here, GPL does not prohibit you to dual-license the code you've written yourself. There is lots of software which does it this way. That's what I suggest you to do. But please do it explicitly, otherwise, not having this done explicitly, only GPL terms apply and the whole code becomes "GPL only".

**Comment by IvanPizhenko** [comment]
Btw, GPL itself does not prohibit commercial use. It prohibits closing the code.

**Comment by paulej** [comment]
OK, I added this.  I took that from the Linux source distribution published at aescrypt.com. :)

Hopefully that will suffice.
