### ISSUE TITLE
[Windows] Fix icon of .aes files

### ISSUE THREAD

**Issue by xmha97** [paulej/AESCrypt#31]
Now you using a 256x256 icon.

But in the Windows Explorer, the icon is small!

![image](https://user-images.githubusercontent.com/23485114/191363765-2fc98582-5a52-46dd-9ac4-9fbf3d3b5c5a.png)

Please fix this issue.

Thanks

**Comment by paulej** [comment]
This one really isn't important, so perhaps I'll fix this the next time I create a Windows build.  That's not likely to be soon, though.
