### ISSUE TITLE
Using Aescrypt for 128 bit key encryption

### ISSUE THREAD

**Issue by parijohn** [paulej/AESCrypt#8]
Hi, 
I want to use128 bit key for encryption using this code. Is that possible?

**Comment by paulej** [comment]
AES Crypt uses a 256 bit key only. You could modify the code to use a 128 bit key (since the core AES code will accept that key size), but we don't have support for weaker keys in AES Crypt.


-------- Original Message --------

**Comment by joeledwards** [comment]
I believe you would also need to drop from 14 rounds to 11 to stay compatible with other 128-bit implementations.

**Comment by paulej** [comment]
That's done when aes_set_key() is called.  The file aes.c takes care of 
those details.  It's a complete implementation of AES.  AES Crypt just 
uses a subset of the functionality.

Paul

------ Original Message ------
