### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by arget1313** [paulej/AESCrypt#9]
I think it would be better if you don't assume that the file has the ".aes" extension, because with a file with a name of 4 or less characters, the program crashes.

**Comment by paulej** [comment]
Do you see that only with the code here, or also with the version on aescrypt.com? I ask since the versions aren't the same. Also, which platform are you using and what steps lead to this error?

**Comment by arget1313** [comment]
I tested it in both linux versions, this code:
`// assume .aes extension
strncpy(outfile, infile, strlen(infile)-4);
outfile[strlen(infile)-4] = '\0';`
Appears in both.

Look the result:
`arget@kali:~/Escritorio/workplace/aescrypt-3.10/src$ ls
aes.c  aescrypt.c  aescrypt.h  aescrypt_keygen.c  aes.h  keyfile.c  keyfile.h  Makefile  password.c  password.h  sha256.c  sha256.h  version.h
arget@kali:~/Escritorio/workplace/aescrypt-3.10/src$ make
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64 -c aescrypt.c
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64 -c aes.c
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64 -c sha256.c
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64 -c password.c
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64 -c keyfile.c
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64  -o aescrypt aescrypt.o aes.o sha256.o password.o keyfile.o
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64   -c -o aescrypt_keygen.o aescrypt_keygen.c
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64  -o aescrypt_keygen aescrypt_keygen.o password.o
arget@kali:~/Escritorio/workplace/aescrypt-3.10/src$ touch tmp
arget@kali:~/Escritorio/workplace/aescrypt-3.10/src$ aescrypt -d -p pass tmp
Segmentation fault
arget@kali:~/Escritorio/workplace/aescrypt-3.10/src$ `

**Comment by paulej** [comment]
Arget,

Yeah, that's not good. :-)

Let me put that on the to-do list.  I would personally prefer to add 
.aes to the end of files as a default and to remove it as a default.  
Gzip does this, for example. It just needs to be properly handled.  
Clearly, not checking for the file name length was a bad decision.

Paul

------ Original Message ------
